export const API_REQUEST_SUCCESS = "API_REQUEST_SUCCESS";

export const API_REQUEST_ERROR = "API_REQUEST_ERROR";

export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const CHANGE_MODAL_STATE = "CHANGE_MODAL_STATE";
export const CHANGE_EDIT_MODAL_STATE = "CHANGE_EDIT_MODAL_STATE";

export const SET_EDIT_OBJECT = "SET_EDIT_OBJECT";

export const SET_EDIT_OBJECT_FINISH = "SET_EDIT_OBJECT_FINISH";
export const CHANGE_ALERT_MODAL_STATE = "CHANGE_ALERT_MODAL_STATE";

export const SET_DELETE_OBJECT = "SET_DELETE_OBJECT";

export const SORT_PRODUCTS = "SORT_PRODUCTS";
